language: node_js
node_js: node
script: npm test
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
after_deploy:
  - node_modules/.bin/donejs-deploy
deploy:
  skip_cleanup: true
  provider: heroku
  app: stormy-bastion-6513
  api_key:
    secure: hjjeQkU5cKvKHfWFjX6TFjloBEOl4oEoLaRu81DziX2JVVGSNaI77gxJ242SQZGliW1Fsz8uZUNBLHlS89HvANGpSz9nTdbnBDMtDGHONSEIiLvb8MoFoQWWAd1dDOW7APWjScy2iPjzQWa6fCc/HHR+MgRtDMpF8YThWGMbWrIt5wIMmRJGei8TQbFOAKg3bKwQPW+yJb/73zpbpl6LSFuP5cyjzWkvopOE8iaH7Cs2bPfnqXowdrC8umDHIOCua+JFDgTgyKoglNmsnrxBUl3UzsQnWvIjZLwrTAc9kcUJ37aN9/eS2i2/wdRQoXogZrH+OhOwUjW0jkXTn2wfxQTwAwYJle2gTfxiAC0PhxWXw7l+Ecs7bzCRC1V3FCxKbT4OS3zYLqLkXyCNWrMtvlvMTvdIcxTudHlTosvJsibOiAWTVqcnRdsv3BoMvEdBgIPBphSpCb41y2Ukd/4pDczVUqeDvDDtAlgkUxYeihcBrIT97E7L0ZO2rfl+wX1u5tfGe1OxcHizjvIMH5kaCyabjGzFHRyiPcnobPR4/qAJ3en5HAijUaBXEbCTFxxHFMhAhQjiZ705FsM9QdgIFKT0ZizocehzHk+1yEV06Dtc62cVN+9JzwyiCIH4LDDN3YCTV5nRjRTCY56ktFVCVBc9NjFxQqTQXY/MHQb0cHs=
