language: node_js
node_js: node
script: npm test
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
deploy:
  skip_cleanup: true
  provider: "heroku"
  before_deploy: node_modules/.bin/donejs-deploy
